# Generated by Django 5.2.4 on 2025-07-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Literature",
            fields=[
                ("liter_id", models.IntegerField(primary_key=True, serialize=False)),
                ("liter_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("type_id", models.IntegerField()),
                ("text", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "literature",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LiteratureEmotionSummary",
            fields=[
                ("liter_id", models.IntegerField(primary_key=True, serialize=False)),
                ("liter_name", models.CharField(max_length=100)),
                ("total_comments", models.IntegerField()),
                ("positive_count", models.IntegerField()),
                ("neutral_count", models.IntegerField()),
                ("negative_count", models.IntegerField()),
                ("positive_ratio", models.DecimalField(decimal_places=3, max_digits=8)),
            ],
            options={
                "db_table": "literature_emotion_summary",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DailyStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("emotion", models.CharField(max_length=20)),
                ("actual_progress", models.CharField(max_length=100)),
                ("remark", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "daily_status",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ReadingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100)),
                ("plan_content", models.TextField()),
                ("current_progress", models.CharField(max_length=100)),
                ("last_update", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "reading_plan",
                "managed": True,
            },
        ),
    ]
