# Generated by Django 5.2.4 on 2025-07-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailystatus",
            options={},
        ),
        migrations.AlterModelOptions(
            name="readingplan",
            options={},
        ),
    ]
